src/Entity/Heros.php
<?php

namespace App\Entity;

use App\Repository\HerosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: HerosRepository::class)]
class Heros
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $avatar = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_naissance = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Classe $classe = null;

    #[ORM\Column]
    private ?int $ATT = null;

    #[ORM\Column]
    private ?int $DEF = null;

    #[ORM\Column]
    private ?int $PV = null;

    #[ORM\Column]
    private ?int $VIT = null;

    #[ORM\Column]
    private ?int $niveau = null;

    #[ORM\Column]
    private ?int $experience = null;

    #[ORM\Column]
    private ?int $fonds = null;
    
    #[ORM\ManyToOne]
    private ?CouvreChef $couvre_chef = null;

    #[ORM\ManyToOne]
    private ?Bras $bras = null;

    #[ORM\ManyToOne]
    private ?Torse $torse = null;

    #[ORM\ManyToOne]
    private ?Jambes $jambes = null;

    #[ORM\ManyToOne]
    private ?Pieds $pieds = null;

    #[ORM\ManyToOne]
    private ?Armes $armes = null;

    #[ORM\ManyToOne]
    private ?Monture $monture = null;

    #[ORM\Column]
    private ?int $ATT_avec_equipement = null;

    #[ORM\Column]
    private ?int $DEF_avec_equipement = null;

    #[ORM\Column]
    private ?int $PV_avec_equipement = null;

    #[ORM\Column]
    private ?int $VIT_avec_equipement = null;

    public function __construct()
    {
        $this->competences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getClasse(): ?Classe
    {
        return $this->classe;
    }

    public function setClasse(?Classe $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

    public function getATT(): ?int
    {
        return $this->ATT;
    }

    public function setATT(int $ATT): self
    {
        $this->ATT = $ATT;

        return $this;
    }

    public function getDEF(): ?int
    {
        return $this->DEF;
    }

    public function setDEF(int $DEF): self
    {
        $this->DEF = $DEF;

        return $this;
    }

    public function getPV(): ?int
    {
        return $this->PV;
    }

    public function setPV(int $PV): self
    {
        $this->PV = $PV;

        return $this;
    }

    public function getVIT(): ?int
    {
        return $this->VIT;
    }

    public function setVIT(int $VIT): self
    {
        $this->VIT = $VIT;

        return $this;
    }

    public function getNiveau(): ?int
    {
        return $this->niveau;
    }

    public function setNiveau(int $niveau): self
    {
        $this->niveau = $niveau;

        return $this;
    }

    public function getExperience(): ?int
    {
        return $this->experience;
    }

    public function setExperience(int $experience): self
    {
        $this->experience = $experience;

        return $this;
    }
    public function getFonds(): ?int
    {
        return $this->fonds;
    }

    public function setFonds(int $fonds): self
    {
        $this->fonds = $fonds;

        return $this;
    }

    public function getCouvreChef(): ?CouvreChef
    {
        return $this->couvre_chef;
    }

    public function setCouvreChef(?CouvreChef $couvre_chef): self
    {
        $this->couvre_chef = $couvre_chef;

        return $this;
    }

    public function getBras(): ?Bras
    {
        return $this->bras;
    }

    public function setBras(?Bras $bras): self
    {
        $this->bras = $bras;

        return $this;
    }

    public function getTorse(): ?Torse
    {
        return $this->torse;
    }

    public function setTorse(?Torse $torse): self
    {
        $this->torse = $torse;

        return $this;
    }

    public function getJambes(): ?Jambes
    {
        return $this->jambes;
    }

    public function setJambes(?Jambes $jambes): self
    {
        $this->jambes = $jambes;

        return $this;
    }

    public function getPieds(): ?Pieds
    {
        return $this->pieds;
    }

    public function setPieds(?Pieds $pieds): self
    {
        $this->pieds = $pieds;

        return $this;
    }

    public function getArmes(): ?Armes
    {
        return $this->armes;
    }

    public function setArmes(?Armes $armes): self
    {
        $this->armes = $armes;

        return $this;
    }

    public function getMonture(): ?Monture
    {
        return $this->monture;
    }

    public function setMonture(?Monture $monture): self
    {
        $this->monture = $monture;

        return $this;
    }

    public function getATTAvecEquipement(): ?int
    {
        return $this->ATT_avec_equipement;
    }

    public function setATTAvecEquipement(int $ATT_avec_equipement): self
    {
        $this->ATT_avec_equipement = $ATT_avec_equipement;

        return $this;
    }

    public function getDEFAvecEquipement(): ?int
    {
        return $this->DEF_avec_equipement;
    }

    public function setDEFAvecEquipement(int $DEF_avec_equipement): self
    {
        $this->DEF_avec_equipement = $DEF_avec_equipement;

        return $this;
    }

    public function getPVAvecEquipement(): ?int
    {
        return $this->PV_avec_equipement;
    }

    public function setPVAvecEquipement(int $PV_avec_equipement): self
    {
        $this->PV_avec_equipement = $PV_avec_equipement;

        return $this;
    }

    public function getVITAvecEquipement(): ?int
    {
        return $this->VIT_avec_equipement;
    }

    public function setVITAvecEquipement(int $VIT_avec_equipement): self
    {
        $this->VIT_avec_equipement = $VIT_avec_equipement;

        return $this;
    }

}

src/Controller/HerosController.php
<?php

namespace App\Controller;

use App\Entity\Heros;
use App\Form\HerosType;
use App\Repository\HerosRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/heros')]
class HerosController extends AbstractController
{
    #[Route('/', name: 'app_heros_index', methods: ['GET'])]
    public function index(HerosRepository $herosRepository): Response
    {
        return $this->render('heros/index.html.twig', [
            'heros' => $herosRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_heros_new', methods: ['GET', 'POST'])]
    public function new(Request $request, HerosRepository $herosRepository): Response
    {
        $hero = new Heros();
        $form = $this->createForm(HerosType::class, $hero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hero->setATT($hero->getNiveau()*0.25*$hero->getClasse()->getBaseATT()+3*$hero->getClasse()->getBaseATT());
            $hero->setDEF($hero->getNiveau()*0.2*$hero->getClasse()->getBaseDEF()+3*$hero->getClasse()->getBaseDEF());
            $hero->setPV($hero->getNiveau()*0.3*$hero->getClasse()->getBasePV()+3*$hero->getClasse()->getBasePV());
            $hero->setVIT($hero->getNiveau()*0.1*$hero->getClasse()->getBaseVIT()+3*$hero->getClasse()->getBaseVIT());
            $AttApresEquip=$hero->getATT();
            $DefApresEquip=$hero->getDEF();
            $PvApresEquip=$hero->getPV();
            $VitApresEquip=$hero->getVIT();
            if(null!==$hero->getArmes()){
                $AttApresEquip=$AttApresEquip+$hero->getArmes()->getFlatATT()+($hero->getArmes()->getmultATT()/100)*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getArmes()->getFlatDEF()+($hero->getArmes()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getArmes()->getFlatPV()+($hero->getArmes()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getArmes()->getFlatVIT()+($hero->getArmes()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getCouvreChef()){
                $AttApresEquip=$AttApresEquip+$hero->getCouvreChef()->getFlatATT()+($hero->getCouvreChef()->getmultATT()/100)*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getCouvreChef()->getFlatDEF()+($hero->getCouvreChef()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getCouvreChef()->getFlatPV();
                $VitApresEquip=$VitApresEquip+$hero->getCouvreChef()->getFlatVIT()+($hero->getCouvreChef()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getTorse()){
                $AttApresEquip=$AttApresEquip+$hero->getTorse()->getFlatATT()+$hero->getTorse()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getTorse()->getFlatDEF()+($hero->getTorse()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getTorse()->getFlatPV()+($hero->getTorse()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getTorse()->getFlatVIT()+($hero->getTorse()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getBras()){
                $AttApresEquip=$AttApresEquip+$hero->getBras()->getFlatATT()+$hero->getBras()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getBras()->getFlatDEF()+($hero->getBras()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getBras()->getFlatPV()+($hero->getBras()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getBras()->getFlatVIT()+($hero->getBras()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getJambes()){
                $AttApresEquip=$AttApresEquip+$hero->getJambes()->getFlatATT()+$hero->getJambes()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getJambes()->getFlatDEF()+($hero->getJambes()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getJambes()->getFlatPV()+($hero->getJambes()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getJambes()->getFlatVIT()+($hero->getJambes()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getPieds()){
                $AttApresEquip=$AttApresEquip+$hero->getPieds()->getFlatATT()+$hero->getPieds()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getPieds()->getFlatDEF()+($hero->getPieds()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getPieds()->getFlatPV()+($hero->getPieds()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getPieds()->getFlatVIT()+($hero->getPieds()->getmultVIT()/100)*$hero->getVIT();            
            }
            if(null!==$hero->getMonture()){
                $AttApresEquip=$AttApresEquip+$hero->getPieds()->getFlatATT()+$hero->getMonture()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getPieds()->getFlatDEF()+($hero->getPieds()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getPieds()->getFlatPV()+($hero->getPieds()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getPieds()->getFlatVIT()+($hero->getPieds()->getmultVIT()/100)*$hero->getVIT();
            }
            $hero->setATTAvecEquipement( $AttApresEquip);
            $hero->setDEFAvecEquipement($DefApresEquip);
            $hero->setPVAvecEquipement( $PvApresEquip);
            $hero->setVITAvecEquipement( $VitApresEquip);
            $herosRepository->save($hero, true);
            return $this->redirectToRoute('app_heros_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('heros/new.html.twig', [
            'hero' => $hero,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_heros_show', methods: ['GET'])]
    public function show(Heros $hero): Response
    {
        return $this->render('heros/show.html.twig', [
            'hero' => $hero,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_heros_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Heros $hero, HerosRepository $herosRepository): Response
    {
        $form = $this->createForm(HerosType::class, $hero);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hero->setATT($hero->getNiveau()*0.25*$hero->getClasse()->getBaseATT()+3*$hero->getClasse()->getBaseATT());
            $hero->setDEF($hero->getNiveau()*0.2*$hero->getClasse()->getBaseDEF()+3*$hero->getClasse()->getBaseDEF());
            $hero->setPV($hero->getNiveau()*0.3*$hero->getClasse()->getBasePV()+3*$hero->getClasse()->getBasePV());
            $hero->setVIT($hero->getNiveau()*0.1*$hero->getClasse()->getBaseVIT()+3*$hero->getClasse()->getBaseVIT());
            $AttApresEquip=$hero->getATT();
            $DefApresEquip=$hero->getDEF();
            $PvApresEquip=$hero->getPV();
            $VitApresEquip=$hero->getVIT();
            if(null!==$hero->getArmes()){
                $AttApresEquip=$AttApresEquip+$hero->getArmes()->getFlatATT()+($hero->getArmes()->getmultATT()/100)*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getArmes()->getFlatDEF()+($hero->getArmes()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getArmes()->getFlatPV()+($hero->getArmes()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getArmes()->getFlatVIT()+($hero->getArmes()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getCouvreChef()){
                $AttApresEquip=$AttApresEquip+$hero->getCouvreChef()->getFlatATT()+($hero->getCouvreChef()->getmultATT()/100)*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getCouvreChef()->getFlatDEF()+($hero->getCouvreChef()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getCouvreChef()->getFlatPV();
                $VitApresEquip=$VitApresEquip+$hero->getCouvreChef()->getFlatVIT()+($hero->getCouvreChef()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getTorse()){
                $AttApresEquip=$AttApresEquip+$hero->getTorse()->getFlatATT()+$hero->getTorse()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getTorse()->getFlatDEF()+($hero->getTorse()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getTorse()->getFlatPV()+($hero->getTorse()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getTorse()->getFlatVIT()+($hero->getTorse()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getBras()){
                $AttApresEquip=$AttApresEquip+$hero->getBras()->getFlatATT()+$hero->getBras()->getmultATT()/100*$hero->getATT();
                $DefApresEquip=$DefApresEquip+$hero->getBras()->getFlatDEF()+($hero->getBras()->getmultDEF()/100)*$hero->getDEF();
                $PvApresEquip=$PvApresEquip+$hero->getBras()->getFlatPV()+($hero->getBras()->getmultPV()/100)*$hero->getPV();
                $VitApresEquip=$VitApresEquip+$hero->getBras()->getFlatVIT()+($hero->getBras()->getmultVIT()/100)*$hero->getVIT();
            }
            if(null!==$hero->getJambes()){
                $AttApresEquip=$AttApresEquip+$hero->getJambes()->getFlatATT()+$hero->getJambes()->getmultATT()/100*$hero->getATT();

templates/heros/_delete_form.html.twig
<form method="post" action="{{ path('app_heros_delete', {'id': hero.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ hero.id) }}">
    <button class="btn">Delete</button>
</form>

templates/heros/_form.html.twig
{{ form_start(form) }}

<div class="row">
    <div class="col-md-3">{{form_row(form.nom)}}</div>
    <div class="col-md-3">{{form_row(form.niveau)}}</div>
    <div class="col-md-3">{{form_row(form.experience)}}</div>
    <div class="col-md-3">{{form_row(form.fonds)}}</div>
</div>
<div class="row">
    <div class="col-md-10">{{form_row(form.description)}}</div>
</div>
<div class="row">
    <div class="col-md-3">{{form_row(form.avatar)}}</div>
    <div class="col-md-2">{{form_row(form.classe)}}</div>
</div>
<div class="row">
    <div class="col-md-3">{{form_row(form.date_de_naissance)}}</div>
</div>

<div class="row">
    <div class="col-md-2">{{form_row(form.couvre_chef)}}</div>
    <div class="col-md-2">{{form_row(form.bras)}}</div>
    <div class="col-md-2">{{form_row(form.torse)}}</div>
    <div class="col-md-2">{{form_row(form.jambes)}}</div>
    <div class="col-md-2">{{form_row(form.pieds)}}</div>
</div>
<div class="row">
    <div class="col-md-2">{{form_row(form.armes)}}</div>
    <div class="col-md-2">{{form_row(form.monture)}}</div>
</div>


    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/heros/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Edit Heros</h1>

    {{ include('heros/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_heros_index') }}">back to list</a>

    {{ include('heros/_delete_form.html.twig') }}
{% endblock %}

templates/heros/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Heros index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Classe</th>
                <th>Nom</th>
                <th>Avatar</th>
                <th>Description</th>
                <th>Date de naissance</th>
                <th>Niveau</th>
                <th>Experience</th>
                <th>Fonds</th>
                <th>ATT</th>
                <th>DEF</th>
                <th>PV</th>
                <th>VIT</th>                           
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for hero in heros %}
            <tr>
                <td>{{ hero.classe }}</td>
                <td>{{ hero.nom }}</td>
                <td><img class="portrait" src="{{ hero.avatar }}" alt=""></td>
                <td>{{ hero.description }}</td>
                <td>{{ hero.dateDeNaissance ? hero.dateDeNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ hero.niveau }}</td>
                <td>{{ hero.experience }}</td>
                <td>{{ hero.fonds }}</td>
                <td>{{ hero.ATTAvecEquipement }}</td>
                <td>{{ hero.DEFAvecEquipement }}</td>
                <td>{{ hero.PVAvecEquipement }}</td>
                <td>{{ hero.VITAvecEquipement }}</td>


                <td>
                    <a href="{{ path('app_heros_show', {'id': hero.id}) }}">show</a>
                    <a href="{{ path('app_heros_edit', {'id': hero.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_heros_new') }}">Create new</a>
{% endblock %}

templates/heros/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Create new Heros</h1>

    {{ include('heros/_form.html.twig') }}
{% endblock %}

templates/heros/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="entete-profil flex-row margin-bot-5">
    <h1>{{ hero.nom }}</h1>
			<div class="profile-image ">
				<img class="portrait" src="{{ hero.avatar }}" alt="">
			</div>
</div>
    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ hero.id }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ hero.description }}</td>
            </tr>
            <tr>
                <th>Date de naissance</th>
                <td>{{ hero.dateDeNaissance ? hero.dateDeNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>ATT</th>
                <td>{{ hero.ATT }}</td>
            </tr>
            <tr>
                <th>DEF</th>
                <td>{{ hero.DEF }}</td>
            </tr>
            <tr>
                <th>PV</th>
                <td>{{ hero.PV }}</td>
            </tr>
            <tr>
                <th>VIT</th>
                <td>{{ hero.VIT }}</td>
            </tr>
            <tr>
                <th>Niveau</th>
                <td>{{ hero.niveau }}</td>
            </tr>
            <tr>
                <th>Experience</th>
                <td>{{ hero.experience }}</td>
            </tr>
            <tr>
                <th>Fonds</th>
                <td>{{ hero.fonds }}</td>
            </tr>
            <tr>
                <th>ATT totale</th>
                <td>{{ hero.ATTAvecEquipement }}</td>
            </tr>
            <tr>
                <th>DEF totale</th>
                <td>{{ hero.DEFAvecEquipement }}</td>
            </tr>
            <tr>
                <th>PV totaux</th>
                <td>{{ hero.PVAvecEquipement }}</td>
            </tr>
            <tr>
                <th>VIT totale</th>
                <td>{{ hero.VITAvecEquipement }}</td>
            </tr>
            <tr>
                <th>Arme</th>
                <td>{{ hero.armes }}</td>
            </tr>
             <tr>
                <th>Casque</th>
                <td>{{ hero.couvreChef }}</td>
            </tr>           
            <tr>
                <th>Plastron</th>
                <td>{{ hero.torse }}</td>
            </tr>
            <tr>
                <th>Brassards</th>
                <td>{{ hero.bras }}</td>
            </tr>
            <tr>
                <th>Jambes</th>
                <td>{{ hero.jambes }}</td>
            </tr>
            <tr>
                <th>Chaussures</th>
                <td>{{ hero.pieds }}</td>
            </tr>                                                                
            <tr>
                <th>Monture</th>
                <td>{{ hero.monture }}</td>
            </tr>

                
                
                
        </tbody>
    </table>

    <a href="{{ path('app_heros_index') }}">back to list</a>

    <a href="{{ path('app_heros_edit', {'id': hero.id}) }}">edit</a>

    {{ include('heros/_delete_form.html.twig') }}
{% endblock %}