src/Entity/Classe.php
<?php

namespace App\Entity;

use App\Repository\ClasseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClasseRepository::class)]
class Classe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $base_ATT = null;

    #[ORM\Column]
    private ?int $base_DEF = null;

    #[ORM\Column]
    private ?int $base_PV = null;

    #[ORM\Column]
    private ?int $base_VIT = null;

    #[ORM\ManyToMany(targetEntity: Competences::class)]
    private Collection $competences;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    public function __construct()
    {
        $this->competences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->nom;
    }
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getBaseATT(): ?int
    {
        return $this->base_ATT;
    }

    public function setBaseATT(int $base_ATT): self
    {
        $this->base_ATT = $base_ATT;

        return $this;
    }

    public function getBaseDEF(): ?int
    {
        return $this->base_DEF;
    }

    public function setBaseDEF(int $base_DEF): self
    {
        $this->base_DEF = $base_DEF;

        return $this;
    }

    public function getBasePV(): ?int
    {
        return $this->base_PV;
    }

    public function setBasePV(int $base_PV): self
    {
        $this->base_PV = $base_PV;

        return $this;
    }

    public function getBaseVIT(): ?int
    {
        return $this->base_VIT;
    }

    public function setBaseVIT(int $base_VIT): self
    {
        $this->base_VIT = $base_VIT;

        return $this;
    }

    /**
     * @return Collection<int, Competences>
     */
    public function getCompetences(): Collection
    {
        return $this->competences;
    }

    public function addCompetence(Competences $competence): self
    {
        if (!$this->competences->contains($competence)) {
            $this->competences->add($competence);
        }

        return $this;
    }

    public function removeCompetence(Competences $competence): self
    {
        $this->competences->removeElement($competence);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ClasseType.php
<?php

namespace App\Form;

use App\Entity\Classe;
use App\Entity\Competences;
use App\Repository\CompetencesRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use testForm;

class ClasseType extends AbstractType
{
    public function __construct(private UrlGeneratorInterface $url)
    {
        
    }
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('base_ATT',null,[
                'label'=>'Attaque'
            ])
            ->add('base_DEF',null,[
                'label'=>'Defense'
            ])
            ->add('base_PV',null,[
                'label'=>'Points de vie'
            ])
            ->add('base_VIT',null,[
                'label'=>'Vitesse'
            ])
            ->add('competences'
            ,ChoixMultiple::class,[
                'class'=>Competences::class,
                'multiple'=>true,
                'search'=>$this->url->generate('competences'),
            ])
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Classe::class,
        ]);
    }
}

src/Controller/ClasseController.php
<?php

namespace App\Controller;

use App\Entity\Classe;
use App\Form\ClasseType;
use App\Repository\ClasseRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/classe')]
class ClasseController extends AbstractController
{
    #[Route('/', name: 'app_classe_index', methods: ['GET'])]
    public function index(ClasseRepository $classeRepository): Response
    {
        return $this->render('classe/index.html.twig', [
            'classes' => $classeRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_classe_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClasseRepository $classeRepository): Response
    {
        $classe = new Classe();
        $form = $this->createForm(ClasseType::class, $classe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $classeRepository->save($classe, true);

            return $this->redirectToRoute('app_classe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('classe/new.html.twig', [
            'classe' => $classe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_classe_show', methods: ['GET'])]
    public function show(Classe $classe): Response
    {
        return $this->render('classe/show.html.twig', [
            'classe' => $classe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_classe_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Classe $classe, ClasseRepository $classeRepository): Response
    {
        $form = $this->createForm(ClasseType::class, $classe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $classeRepository->save($classe, true);

            return $this->redirectToRoute('app_classe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('classe/edit.html.twig', [
            'classe' => $classe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_classe_delete', methods: ['POST'])]
    public function delete(Request $request, Classe $classe, ClasseRepository $classeRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$classe->getId(), $request->request->get('_token'))) {
            $classeRepository->remove($classe, true);
        }

        return $this->redirectToRoute('app_classe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/classe/_delete_form.html.twig
<form method="post" action="{{ path('app_classe_delete', {'id': classe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ classe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/classe/_form.html.twig
{{ form_start(form) }}
<div class="row">
    <div class="col-md-3">{{form_row(form.nom)}}</div>
    <div>{{form_row(form.competences)}}</div>
</div>
<div class="row">
    <div>{{form_row(form.description)}}</div>
</div>
<div class="row">
    <div class="col-md-3">{{form_row(form.base_ATT)}}</div>
    <div class="col-md-3">{{form_row(form.base_DEF)}}</div>
    <div class="col-md-3">{{form_row(form.base_PV)}}</div>
    <div class="col-md-3">{{form_row(form.base_VIT)}}</div>
</div>
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/classe/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Edit Classe</h1>

    {{ include('classe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_classe_index') }}">back to list</a>

    {{ include('classe/_delete_form.html.twig') }}
{% endblock %}

templates/classe/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Classe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>ATT de base</th>
                <th>DEF de base</th>
                <th>PV de base</th>
                <th>VIT de base</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for classe in classes %}
            <tr>
                <td>{{ classe.nom }}</td>
                <td>{{ classe.baseATT }}</td>
                <td>{{ classe.baseDEF }}</td>
                <td>{{ classe.basePV }}</td>
                <td>{{ classe.baseVIT }}</td>
                <td>
                    <a href="{{ path('app_classe_show', {'id': classe.id}) }}">show</a>
                    <a href="{{ path('app_classe_edit', {'id': classe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_classe_new') }}">Create new</a>
{% endblock %}

templates/classe/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container mt-3 w-60 margil-lat-20">
    <h1>Create new Classe</h1>

    {{ include('classe/_form.html.twig') }}

    </div>
{% endblock %}

templates/classe/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h1>Classe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ classe.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ classe.nom }}</td>
            </tr>
            <tr>
                <th>Base_ATT</th>
                <td>{{ classe.baseATT }}</td>
            </tr>
            <tr>
                <th>Base_DEF</th>
                <td>{{ classe.baseDEF }}</td>
            </tr>
            <tr>
                <th>Base_PV</th>
                <td>{{ classe.basePV }}</td>
            </tr>
            <tr>
                <th>Base_VIT</th>
                <td>{{ classe.baseVIT }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_classe_index') }}">back to list</a>

    <a href="{{ path('app_classe_edit', {'id': classe.id}) }}">edit</a>

    {{ include('classe/_delete_form.html.twig') }}
{% endblock %}