src/Entity/Armes.php
<?php

namespace App\Entity;

use App\Repository\ArmesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArmesRepository::class)]
class Armes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $flat_ATT = null;

    #[ORM\Column]
    private ?int $flat_DEF = null;

    #[ORM\Column]
    private ?int $flat_PV = null;

    #[ORM\Column]
    private ?int $flat_VIT = null;

    #[ORM\Column]
    private ?int $mult_ATT = null;

    #[ORM\Column]
    private ?int $mult_DEF = null;

    #[ORM\Column]
    private ?int $mult_PV = null;

    #[ORM\Column]
    private ?int $mult_VIT = null;

    #[ORM\Column]
    private ?int $prix = null;

    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->nom;
    }
    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFlatATT(): ?int
    {
        return $this->flat_ATT;
    }

    public function setFlatATT(int $flat_ATT): self
    {
        $this->flat_ATT = $flat_ATT;

        return $this;
    }

    public function getFlatDEF(): ?int
    {
        return $this->flat_DEF;
    }

    public function setFlatDEF(int $flat_DEF): self
    {
        $this->flat_DEF = $flat_DEF;

        return $this;
    }

    public function getFlatPV(): ?int
    {
        return $this->flat_PV;
    }

    public function setFlatPV(int $flat_PV): self
    {
        $this->flat_PV = $flat_PV;

        return $this;
    }

    public function getFlatVIT(): ?int
    {
        return $this->flat_VIT;
    }

    public function setFlatVIT(int $flat_VIT): self
    {
        $this->flat_VIT = $flat_VIT;

        return $this;
    }

    public function getMultATT(): ?int
    {
        return $this->mult_ATT;
    }

    public function setMultATT(int $mult_ATT): self
    {
        $this->mult_ATT = $mult_ATT;

        return $this;
    }

    public function getMultDEF(): ?int
    {
        return $this->mult_DEF;
    }

    public function setMultDEF(int $mult_DEF): self
    {
        $this->mult_DEF = $mult_DEF;

        return $this;
    }

    public function getMultPV(): ?int
    {
        return $this->mult_PV;
    }

    public function setMultPV(int $mult_PV): self
    {
        $this->mult_PV = $mult_PV;

        return $this;
    }

    public function getMultVIT(): ?int
    {
        return $this->mult_VIT;
    }

    public function setMultVIT(int $mult_VIT): self
    {
        $this->mult_VIT = $mult_VIT;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Form/ArmesType.php
<?php

namespace App\Form;

use App\Entity\Armes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArmesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('flat_ATT')
            ->add('flat_DEF')
            ->add('flat_PV')
            ->add('flat_VIT')
            ->add('mult_ATT')
            ->add('mult_DEF')
            ->add('mult_PV')
            ->add('mult_VIT')
            ->add('prix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Armes::class,
        ]);
    }
}

src/Controller/ArmesController.php
<?php

namespace App\Controller;

use App\Entity\Armes;
use App\Form\ArmesType;
use App\Repository\ArmesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/armes')]
class ArmesController extends AbstractController
{
    #[Route('/', name: 'app_armes_index', methods: ['GET'])]
    public function index(ArmesRepository $armesRepository): Response
    {
        return $this->render('armes/index.html.twig', [
            'armes' => $armesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_armes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArmesRepository $armesRepository): Response
    {
        $arme = new Armes();
        $form = $this->createForm(ArmesType::class, $arme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $armesRepository->save($arme, true);

            return $this->redirectToRoute('app_armes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('armes/new.html.twig', [
            'arme' => $arme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_armes_show', methods: ['GET'])]
    public function show(Armes $arme): Response
    {
        return $this->render('armes/show.html.twig', [
            'arme' => $arme,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_armes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Armes $arme, ArmesRepository $armesRepository): Response
    {
        $form = $this->createForm(ArmesType::class, $arme);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $armesRepository->save($arme, true);

            return $this->redirectToRoute('app_armes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('armes/edit.html.twig', [
            'arme' => $arme,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_armes_delete', methods: ['POST'])]
    public function delete(Request $request, Armes $arme, ArmesRepository $armesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$arme->getId(), $request->request->get('_token'))) {
            $armesRepository->remove($arme, true);
        }

        return $this->redirectToRoute('app_armes_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/armes/_delete_form.html.twig
<form method="post" action="{{ path('app_armes_delete', {'id': arme.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ arme.id) }}">
    <button class="btn">Delete</button>
</form>

templates/armes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Armes{% endblock %}

{% block body %}
    <h1>Edit Armes</h1>

    {{ include('armes/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_armes_index') }}">back to list</a>

    {{ include('armes/_delete_form.html.twig') }}
{% endblock %}

templates/armes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Armes index{% endblock %}

{% block body %}
    <h1>Armes index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>ATT ajoutés</th>
                <th>DEF ajoutés</th>
                <th>PV ajoutés</th>
                <th>VIT ajoutés</th>
                <th>Multiplicateur ATT </th>
                <th>Multiplicateur DEF</th>
                <th>Multiplicateur PV</th>
                <th>Multiplicateur VIT</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for arme in armes %}
            <tr>
                <td>{{ arme.id }}</td>
                <td>{{ arme.nom }}</td>
                <td>{{ arme.description }}</td>
                <td>{{ arme.flatATT }}</td>
                <td>{{ arme.flatDEF }}</td>
                <td>{{ arme.flatPV }}</td>
                <td>{{ arme.flatVIT }}</td>
                <td>{{ arme.multATT }}</td>
                <td>{{ arme.multDEF }}</td>
                <td>{{ arme.multPV }}</td>
                <td>{{ arme.multVIT }}</td>
                <td>{{ arme.prix }}</td>
                <td>
                    <a href="{{ path('app_armes_show', {'id': arme.id}) }}">show</a>
                    <a href="{{ path('app_armes_edit', {'id': arme.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_armes_new') }}">Create new</a>
{% endblock %}

templates/armes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Armes{% endblock %}

{% block body %}
    <h1>Create new Armes</h1>

    {{ include('armes/_form.html.twig') }}

{% endblock %}

templates/armes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Armes{% endblock %}

{% block body %}
    <h1>Armes</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ arme.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ arme.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ arme.description }}</td>
            </tr>
            <tr>
                <th>Flat_ATT</th>
                <td>{{ arme.flatATT }}</td>
            </tr>
            <tr>
                <th>Flat_DEF</th>
                <td>{{ arme.flatDEF }}</td>
            </tr>
            <tr>
                <th>Flat_PV</th>
                <td>{{ arme.flatPV }}</td>
            </tr>
            <tr>
                <th>Flat_VIT</th>
                <td>{{ arme.flatVIT }}</td>
            </tr>
            <tr>
                <th>Mult_ATT</th>
                <td>{{ arme.multATT }}</td>
            </tr>
            <tr>
                <th>Mult_DEF</th>
                <td>{{ arme.multDEF }}</td>
            </tr>
            <tr>
                <th>Mult_PV</th>
                <td>{{ arme.multPV }}</td>
            </tr>
            <tr>
                <th>Mult_VIT</th>
                <td>{{ arme.multVIT }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ arme.prix }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_armes_index') }}">back to list</a>

    <a href="{{ path('app_armes_edit', {'id': arme.id}) }}">edit</a>

    {{ include('armes/_delete_form.html.twig') }}
{% endblock %}